FROM python:3.7-alpine

ENV APP_HOME=/usr/src/app
WORKDIR /usr/src/app

ENV PYTHONBUFFERED 1
ENV PYTHONWRITEBYTECODE 1

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN addgroup -S app && adduser --home /usr/src/app --shell /bin/bash -S app -G app

COPY Requirements.txt $APP_HOME
RUN pip install --upgrade pip
RUN pip install -r Requirements.txt
COPY . $APP_HOME
# hacer ejecutable
RUN chmod +x entrypoint.sh
#  asignar dueño y grupo
RUN chown -R app:app $APP_HOME

USER app:app

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]